In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
with open('./anna.txt','r') as f:
    text = f.read()

In [11]:
len(text)

1985223

In [4]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

In [5]:
#map each char to an integer and vice-vera
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch:i for i,ch in int2char.items()}

In [6]:
#encode the text
encoded = np.array([char2int[ch] for ch in text])

In [12]:
len(encoded)

1985223

In [7]:
encoded[:100]

array([55, 21, 13, 80, 36, 45, 34, 41,  3, 32, 32, 32, 74, 13, 80, 80, 53,
       41, 42, 13, 43, 25, 57, 25, 45, 31, 41, 13, 34, 45, 41, 13, 57, 57,
       41, 13, 57, 25, 56, 45, 69, 41, 45, 18, 45, 34, 53, 41, 77, 46, 21,
       13, 80, 80, 53, 41, 42, 13, 43, 25, 57, 53, 41, 25, 31, 41, 77, 46,
       21, 13, 80, 80, 53, 41, 25, 46, 41, 25, 36, 31, 41,  4, 78, 46, 32,
       78, 13, 53,  7, 32, 32, 62, 18, 45, 34, 53, 36, 21, 25, 46])

In [8]:
def one_hot_encode(arr,n_labels):
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [9]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


In [10]:
test_seq.size

3